# Generated by Django 5.0.8 on 2025-09-09 14:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidate', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruiterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('preferred_education_levels', models.JSONField(blank=True, default=list)),
                ('preferred_experience_range', models.JSONField(blank=True, default=dict)),
                ('preferred_universities', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil recruteur',
                'verbose_name_plural': 'Profils recruteurs',
            },
        ),
        migrations.CreateModel(
            name='RecruiterSearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_query', models.CharField(max_length=500)),
                ('search_filters', models.JSONField(default=dict)),
                ('results_count', models.IntegerField(default=0)),
                ('search_date', models.DateTimeField(auto_now_add=True)),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique de recherche',
                'verbose_name_plural': 'Historiques de recherches',
                'ordering': ['-search_date'],
            },
        ),
        migrations.CreateModel(
            name='CandidateInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('profile_view', 'Consultation profil'), ('video_view', 'Consultation vidéo'), ('cv_download', 'Téléchargement CV'), ('message_sent', 'Message envoyé'), ('interview_request', 'Demande entretien'), ('offer_sent', 'Offre envoyée'), ('favorite_added', 'Ajout aux favoris'), ('favorite_removed', 'Retrait des favoris')], max_length=20)),
                ('interaction_date', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_interactions', to='candidate.candidateprofile')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interaction candidat',
                'verbose_name_plural': 'Interactions candidats',
                'ordering': ['-interaction_date'],
                'indexes': [models.Index(fields=['candidate', '-interaction_date'], name='recruiter_c_candida_dde8b1_idx'), models.Index(fields=['recruiter', '-interaction_date'], name='recruiter_c_recruit_6d23fc_idx'), models.Index(fields=['interaction_type'], name='recruiter_c_interac_a13937_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProfileViewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('view_duration', models.IntegerField(blank=True, null=True)),
                ('sections_viewed', models.JSONField(blank=True, default=list)),
                ('cv_downloaded', models.BooleanField(default=False)),
                ('video_watched', models.BooleanField(default=False)),
                ('contact_attempted', models.BooleanField(default=False)),
                ('interest_level', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('notes', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('candidate_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_views', to='candidate.candidateprofile')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consultation de profil',
                'verbose_name_plural': 'Consultations de profils',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['candidate_profile', '-viewed_at'], name='recruiter_p_candida_a67c2d_idx'), models.Index(fields=['recruiter', '-viewed_at'], name='recruiter_p_recruit_7d2b12_idx')],
            },
        ),
        migrations.CreateModel(
            name='RecruiterFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('priority', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate.candidateprofile')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Candidat favori',
                'verbose_name_plural': 'Candidats favoris',
                'ordering': ['-added_at'],
                'unique_together': {('recruiter', 'candidate')},
            },
        ),
    ]
