# Generated by Django 5.0.8 on 2025-09-04 16:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('videos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('education_level', models.CharField(blank=True, max_length=100)),
                ('university', models.CharField(blank=True, max_length=200)),
                ('major', models.CharField(blank=True, max_length=200)),
                ('graduation_year', models.IntegerField(blank=True, null=True)),
                ('experience_years', models.IntegerField(default=0)),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='cvs/')),
                ('cv_last_updated', models.DateTimeField(blank=True, null=True)),
                ('portfolio_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('video_last_updated', models.DateTimeField(blank=True, null=True)),
                ('video_quality_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('video_linked_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Recherche active'), ('passive', 'Recherche passive'), ('not_available', 'Non disponible')], default='active', max_length=20)),
                ('is_profile_public', models.BooleanField(default=True)),
                ('accepts_offers', models.BooleanField(default=True)),
                ('preferred_salary_min', models.IntegerField(blank=True, null=True)),
                ('preferred_salary_max', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile_completeness', models.IntegerField(default=0)),
                ('presentation_video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_profile', to='videos.video')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil candidat',
                'verbose_name_plural': 'Profils candidats',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CVVideoSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('cv_version', models.CharField(blank=True, max_length=100)),
                ('video_version', models.CharField(blank=True, max_length=100)),
                ('sync_needed', models.BooleanField(default=False)),
                ('sync_completed', models.BooleanField(default=False)),
                ('sync_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('candidate_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate.candidateprofile')),
            ],
            options={
                'verbose_name': 'Synchronisation CV-Vidéo',
                'verbose_name_plural': 'Synchronisations CV-Vidéo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoViewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('view_duration', models.IntegerField(blank=True, null=True)),
                ('completed_viewing', models.BooleanField(default=False)),
                ('rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('notes', models.TextField(blank=True)),
                ('candidate_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate.candidateprofile')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_logs', to='videos.video')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consultation vidéo',
                'verbose_name_plural': 'Consultations vidéos',
                'ordering': ['-viewed_at'],
            },
        ),
    ]
